# Generated by Django 3.0.8 on 2020-07-29 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balon_num', models.CharField(blank=True, max_length=150)),
                ('balon_status', models.CharField(choices=[('S', 'Склад'), ('G', 'Город')], max_length=150)),
                ('balon_state', models.CharField(choices=[('N', 'Наполнение'), ('O', 'Отбраковано')], max_length=150)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
