# Generated by Django 3.0.8 on 2020-07-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balon_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balon',
            name='balon_state',
            field=models.CharField(blank=True, choices=[('N', 'Наполнение'), ('O', 'Отбраковано')], max_length=150),
        ),
    ]
